##===- lib/Analysis/InstCounter/Makefile -----------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../..
LIBRARYNAME = InstCounter
LOADABLE_MODULE = 1
USEDLIBS = 

include $(LEVEL)/Makefile.common

CXXFLAGS+= -std=c++0x -w